### ISSUE TITLE
KeyError: 'init' for many models

### ISSUE THREAD

**Issue by olupton** [neuronsimulator/nrn-modeldb-ci#19]
When running the full set of models locally, many of them fail with messages like
```
2022-03-22 11:00:20,106 :: ERROR    :: 234111
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 232876
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 234241
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 235320
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 234233
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 235769
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 235052
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
2022-03-22 11:00:20,106 :: ERROR    :: 236310
        Traceback (most recent call last):        File "/gpfs/bbp.cscs.ch/home/olupton/nrn-modeldb-ci/modeldb/modelrun.py", line 234, in run_model          model_run_cmds += [model.run_info["init"], model
.run_info["driver"]]    KeyError: 'init'
```

This looks like an error in the launch scripts that should not be tolerated; i.e. it should have aborted the whole run, but actually these errors were hidden in the logfile.

**Comment by alexsavulescu** [comment]
Was unable to reproduce on my side (but didn't spend that much time on it anyway). We were discussing offline and looks like re-running in the same working directory can interfere with the models: 
```
Example:
%model_dir%/SimData_72/Scripts/SimData_1/Scripts/mosinit.hoc
became
%model_dir%/SimData_72/Scripts/SimData_1/Scripts/SimData_1/Scripts/mosinit.hoc
in model 112685
```

Will add a `clean` option just in case via : #21
